In [4]:
import numpy as np
# create your first array
arr = np.array([1,2,3,4,5], dtype='int32')

In [5]:
arr

array([1, 2, 3, 4, 5], dtype=int32)

In [18]:
arr2= np.array(((1,2,3),(4,5,6)))
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# shape gives the dimension
dimension = arr2.shape
print(dimension)
dimr = arr2.shape[0]
dimc = arr2.shape[1]
[dimr, dimc]

(2, 3)


[2, 3]

In [14]:
# size gives the number of elements
a = np.array([[1,2,3],[4,5,6]])
a_size = a.size
a_size

6

In [25]:
# arrange function
# ( start, stop, stepsize), stop is not included
arr3 = np.arange(10,20,2)
print(arr3)

arr4 = np.arange(1,5, 0.5)
arr4

[10 12 14 16 18]


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [27]:
# linspace
arr5 = np.linspace(2,3,10) # (start, stop, no_of_points)
arr5

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [28]:
# 3D Example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print(f'Size of b = {b.size}')
print(f'Shape of b = {b.shape}')
print(f'Nbyte of b = {b.nbytes}')
print(f'Item size of b = {b.itemsize}')

# Get specific element ( work outside in)
print(b[0,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Size of b = 8
Shape of b = (2, 2, 2)
Nbyte of b = 64
Item size of b = 8
4


In [34]:
# reshape 
a = np.arange(10,25).reshape(3,5)
print(a)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [37]:
# 3D Array
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [40]:
# Matrix manupulation
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[1,2],[3,4]])
m3 = m1 - m2
print(m3)

[[0 0]
 [0 0]]


In [42]:
# Matrix addition
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[1,2],[3,4]])
m3 = m1 * m2 # * does elementwise multiplication
print(m3)

[[ 1  4]
 [ 9 16]]


In [49]:
# Matrix multiplication
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[1,2],[3,4]])
m3 = m1 @ m2 # @ does the matrix multiplication 
print(m3)

[[ 7 10]
 [15 22]]


In [51]:
# Alternative method
m4 = m1.dot(m2)
print(m4)

[[ 7 10]
 [15 22]]


In [63]:
np.sin(m4)

array([[ 0.6569866 , -0.54402111],
       [ 0.65028784, -0.00885131]])